name: PR Build

on:
  push:
    branches-ignore:
      - "main"
      - "master"
    paths-ignore:
      - "*.md"
      - "*.sh"
      - ".github/workflows/release.yaml"
      - ".github/workflows/sync_openlist.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
    paths-ignore:
      - "*.md"
      - "*.sh"
      - ".github/workflows/release.yaml"
      - ".github/workflows/sync_openlist.yaml"

  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      output: "${{ github.workspace }}/build/app/outputs/apk/debug"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download OpenList Source Code
        run: |
          cd $GITHUB_WORKSPACE/openlist-lib/scripts
          chmod +x *.sh
          ./init_openlist.sh
          ./init_web.sh

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build OpenList
        run: |
          cd $GITHUB_WORKSPACE/openlist-lib/scripts
          chmod +x *.sh
          ./init_gomobile.sh
          ./gobind.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: "OpenList-AAR-PR-${{ github.run_number }}"
          path: "${{ github.workspace }}/android/app/libs/*.aar"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
      
      # Build debug APK (uses debug signing automatically)
      - run: flutter build apk --split-per-abi --debug

      - name: Upload missing_rules.txt
        if: failure() && steps.gradle.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: "missing_rules-PR-${{ github.run_number }}"
          path: "${{ github.workspace }}/build/app/outputs/mapping/debug/missing_rules.txt"

      - name: Init APP Version Name
        run: |
          echo "ver_name=$(grep -m 1 'versionName' ${{ env.output }}/output-metadata.json | cut -d'"' -f4)" >> $GITHUB_ENV

      - name: Upload App To Artifact arm64-v8a
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: "OpenListFlutter-PR-v${{ env.ver_name }}_arm64-v8a-${{ github.run_number }}"
          path: "${{ env.output }}/*-v8a.apk"

      - name: Upload App To Artifact arm-v7a
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: "OpenListFlutter-PR-v${{ env.ver_name }}_arm-v7a-${{ github.run_number }}"
          path: "${{ env.output }}/*-v7a.apk"

      - name: Upload App To Artifact x86_64
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: "OpenListFlutter-PR-v${{ env.ver_name }}_x86_64-${{ github.run_number }}"
          path: "${{ env.output }}/*64.apk"

  ios:
    runs-on: macos-latest
    env:
      output: "${{ github.workspace }}/build/ios/ipa"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Download OpenList Source Code
        run: |
          cd $GITHUB_WORKSPACE/openlist-lib/scripts
          chmod +x *.sh
          echo "Initializing OpenList..."
          ./init_openlist.sh
          echo "Initializing Web assets for iOS..."
          ./init_web_ios.sh

      - name: Verify Go Installation
        run: |
          which go
          go version
          echo "GOPATH: $GOPATH"
          echo "GOROOT: $GOROOT"

      - name: Build OpenList for iOS
        run: |
          cd $GITHUB_WORKSPACE/openlist-lib/scripts
          chmod +x *.sh
          echo "Initializing gomobile for iOS..."
          ./init_gomobile.sh
          echo "Checking Go mobile installation..."
          go list -m golang.org/x/mobile 2>/dev/null || echo "mobile module not found"
          which gomobile || echo "gomobile not in PATH"
          which gobind || echo "gobind not in PATH"
          echo "Checking openlistlib directory..."
          ls -la ../openlistlib/ || echo "openlistlib directory not found"
          echo "Checking for problematic imports..."
          if [ -d ../openlistlib ]; then
            echo "Go files in openlistlib:"
            ls -la ../openlistlib/*.go 2>/dev/null || echo "No Go files found"
            echo "Checking imports:"
            grep -r "golang.org/x/mobile/bind" ../openlistlib/ 2>/dev/null || echo "No bind imports found"
          fi
          echo "Building iOS framework..."
          ./gobind_ios.sh

      - name: Upload iOS Framework
        uses: actions/upload-artifact@v4
        with:
          name: "OpenList-iOS-Framework-PR-${{ github.run_number }}"
          path: "${{ github.workspace }}/ios/Frameworks/*.xcframework"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Build iOS App (No Code Sign)
        run: |
          flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          mkdir -p ${{ env.output }}
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ${{ env.output }}/OpenListFlutter-PR.ipa Payload/

      - name: Get App Version
        run: |
          # Get base version from openlist_version file and add timestamp
          BASE_VERSION=$(cat openlist_version)
          # Generate timestamp in format YYMMDDHH (精确到小时)
          TIMESTAMP=$(date +%y%m%d%H)
          # Combine version with timestamp for artifact naming
          echo "ver_name=${BASE_VERSION}.${TIMESTAMP}" >> $GITHUB_ENV

      - name: Upload iOS App To Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: "OpenListFlutter-iOS-PR-${{ env.ver_name }}-${{ github.run_number }}"
          path: "${{ env.output }}/OpenListFlutter-PR.ipa"
